version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER} -h localhost -p ${DB_PORT} -d ${DB_DATABASE}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
